### ISSUE TITLE
Unable to install 1Commerce SFDX plugin

### ISSUE THREAD

**Issue by juandomenechh** [forcedotcom/sfdx-1commerce-plugin#1]
I typed in my terminal the following line, as specified:

`sfdx plugins:install https://github.com/forcedotcom/sfdx-1commerce-plugin`

but got an error that is preventing me to install the plugin:

`Installing plugin https://github.com/forcedotcom/sfdx-1commerce-plugin... info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.Installing plugin https://github.com/forcedotcom/sfdx-1commerce-plugin... failed
warning "https://github.com/forcedotcom/sfdx-1commerce-plugin > tslint-to-eslint-config > eslint-config-prettier@6.11.0" has unmet peer dependency "eslint@>=3.14.1".
error An unexpected error occurred: "https://nexus.soma.salesforce.com/nexus/content/groups/npm-all/tslib/-/tslib-1.13.0.tgz: getaddrinfo ENOTFOUND nexus.soma.salesforce.com".
    Error: yarn --prod --non-interactive --mutex=file:C:\Users\.....`

Couldn't find out what's going wrong.
Any suggestions? Thanks in advance!

**Comment by smolynsf** [comment]
Sorry! The yarn.lock was pointing to the wrong registry.  I've fixed that, please try again.
