### ISSUE TITLE
sfdx plugins:install https://github.com/forcedotcom/sfdx-1commerce-plugin Not working

### ISSUE THREAD

**Issue by dsood27** [forcedotcom/sfdx-1commerce-plugin#16]
error Could not open cafile: ENOENT: no such file or directory, open 'C:\Downloads\DigiCertHighAssuranceEVRootCA.crt'

PS D:\Git\SubscriptionAccerlator\commerce1> sfdx plugins:install https://github.com/forcedotcom/sfdx-1commerce-plugin
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
error Could not open cafile: ENOENT: no such file or directory, open 'C:\Downloads\DigiCertHighAssuranceEVRootCA.crt'
warning https://github.com/forcedotcom/sfdx-1commerce-plugin > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning https://github.com/forcedotcom/sfdx-1commerce-plugin > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning https://github.com/forcedotcom/sfdx-1commerce-plugin > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning https://github.com/forcedotcom/sfdx-1commerce-plugin > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error Could not open cafile: ENOENT: no such file or directory, open 'C:\Downloads\DigiCertHighAssuranceEVRootCA.crt'
error Could not open cafile: ENOENT: no such file or directory, open 'C:\Downloads\DigiCertHighAssuranceEVRootCA.crt'
error Command failed with exit code 2.
error Command failed with exit code 2.
Installing plugin https://github.com/forcedotcom/sfdx-1commerce-plugin... failed
    Error: yarn add https://github.com/forcedotcom/sfdx-1commerce-plugin --non-interactive --mutex=file:C:\Users\devan\AppData\Local\sfdx\yarn.lock 
    --preferred-cache-folder=C:\Users\devan\AppData\Local\sfdx\yarn --check-files exited with code 2
PS D:\Git\SubscriptionAccerlator\commerce1>

**Comment by dsood27** [comment]
@smolynsf

**Comment by tarcang** [comment]
Hello, make sure the salesforce certificates are installed correctly in your machine. I have tried to install the plugin to my machine using "sfdx plugins:install https://github.com/forcedotcom/sfdx-1commerce-plugin" and it have worked fine.
